# Generated by Django 5.0 on 2023-12-16 04:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn" target="_blank">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.author')),
                ('genre', models.ForeignKey(help_text='Select a genre for this book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='genre.genre')),
            ],
            options={
                'ordering': ['title', 'author'],
            },
        ),
    ]
